classes:
	javac -cp . -d bin main/domini/classes/*.java
	javac -cp . -d bin main/domini/controladors/*.java
	javac -cp . -d bin main/persistencia/classes/*.java
    javac -cp . -d bin main/persistencia/controladors/*.java
    javac -cp . -d bin main/persistencia/classes/*.java
    javac -cp . -d bin main/persistencia/controladors/*.java

jar:
    jar cmvf Main.mf Othello.jar -C bin .